title: My training blog
author: Claus
email: cgerull@live.com
description: > # this means to ignore newlines until "baseurl:"
  Not in use for production. Just testing gitHub learning bots.

# social links
twitter_username: cgerull 
github_username:  cgerull

show_excerpts: true # set to false to remove excerpts on the homepage

theme:  jekyll-theme-minimal
